//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlumbingProps.Document {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordParts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlumbingProps.Document.WordParts", typeof(WordParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to val.
        /// </summary>
        internal static string prefijo {
            get {
                return ResourceManager.GetString("prefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:br/&gt;.
        /// </summary>
        internal static string tagEnter {
            get {
                return ResourceManager.GetString("tagEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:tblGrid&gt;.
        /// </summary>
        internal static string tagGrid {
            get {
                return ResourceManager.GetString("tagGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:tc&gt;
        ///      &lt;w:tcPr&gt;
        ///        &lt;w:tcW w:w=&quot;3259&quot; w:type=&quot;dxa&quot; /&gt;
        ///        &lt;w:shd w:val=&quot;clear&quot; w:color=&quot;auto&quot; w:fill=&quot;EEECE1&quot; /&gt;
        ///      &lt;/w:tcPr&gt;
        ///      &lt;w:p wsp:rsidR=&quot;002A7E54&quot; wsp:rsidRPr=&quot;006C7DFD&quot;
        ///      wsp:rsidRDefault=&quot;002A7E54&quot; wsp:rsidP=&quot;006C7DFD&quot;&gt;
        ///        &lt;w:pPr&gt;
        ///          &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:line-rule=&quot;auto&quot; /&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lang w:val=&quot;ES&quot; /&gt;
        ///          &lt;/w:rPr&gt;
        ///        &lt;/w:pPr&gt;
        ///        &lt;w:r wsp:rsidRPr=&quot;006C7DFD&quot;&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagGridCellTitle {
            get {
                return ResourceManager.GetString("tagGridCellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:tc&gt;
        ///      &lt;w:tcPr&gt;
        ///        &lt;w:tcW w:w=&quot;3259&quot; w:type=&quot;dxa&quot; /&gt;
        ///        &lt;w:shd w:val=&quot;clear&quot; w:color=&quot;auto&quot; w:fill=&quot;auto&quot; /&gt;
        ///      &lt;/w:tcPr&gt;
        ///      &lt;w:p wsp:rsidR=&quot;002A7E54&quot; wsp:rsidRPr=&quot;006C7DFD&quot;
        ///      wsp:rsidRDefault=&quot;00446018&quot; wsp:rsidP=&quot;006C7DFD&quot;&gt;
        ///        &lt;w:pPr&gt;
        ///          &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:line-rule=&quot;auto&quot; /&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lang w:val=&quot;ES&quot; /&gt;
        ///          &lt;/w:rPr&gt;
        ///        &lt;/w:pPr&gt;
        ///        &lt;w:r wsp:rsidRPr=&quot;006C7DFD&quot;&gt;
        ///          &lt;w:rPr&gt;
        ///            &lt;w:lan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagGridCellValue {
            get {
                return ResourceManager.GetString("tagGridCellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:gridCol w:w=&quot;{0}&quot; /&gt;.
        /// </summary>
        internal static string tagGridColumn {
            get {
                return ResourceManager.GetString("tagGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/w:tblGrid&gt;.
        /// </summary>
        internal static string tagGridEnd {
            get {
                return ResourceManager.GetString("tagGridEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:tr wsp:rsidR=&quot;002A7E54&quot; wsp:rsidRPr=&quot;006C7DFD&quot;
        ///  wsp:rsidTr=&quot;006C7DFD&quot;&gt;.
        /// </summary>
        internal static string tagGridRow {
            get {
                return ResourceManager.GetString("tagGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/w:tr&gt;.
        /// </summary>
        internal static string tagGridRowEnd {
            get {
                return ResourceManager.GetString("tagGridRowEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p wsp:rsidR=&quot;006956CA&quot; wsp:rsidRDefault=&quot;00D52529&quot; wsp:rsidP=&quot;00D52529&quot;&gt;
        ///    &lt;w:pPr&gt;&lt;w:pStyle w:val=&quot;Prrafodelista&quot;/&gt;
        ///    &lt;w:listPr&gt;
        ///      &lt;w:ilvl w:val=&quot;0&quot;/&gt;
        ///      &lt;w:ilfo w:val=&quot;6&quot;/&gt;&lt;wx:t wx:val=&quot;¨&quot;/&gt;
        ///      &lt;wx:font wx:val=&quot;Wingdings&quot;/&gt;
        ///    &lt;/w:listPr&gt;
        ///      &lt;w:ind w:left=&quot;426&quot; w:hanging=&quot;284&quot;/&gt;
        ///      &lt;w:rPr&gt;&lt;w:rFonts w:cs=&quot;Calibri&quot;/&gt;
        ///        &lt;w:lang w:val=&quot;EN-US&quot;/&gt;&lt;/w:rPr&gt;&lt;/w:pPr&gt;&lt;w:r&gt;&lt;w:rPr&gt;&lt;w:rFonts w:cs=&quot;Calibri&quot;/&gt;
        ///          &lt;w:lang w:val=&quot;EN-US&quot;/&gt;
        ///        &lt;/w:rPr&gt;
        ///          &lt;w:t&gt;  &lt;/w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagNO {
            get {
                return ResourceManager.GetString("tagNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p wsp:rsidR=&quot;006956CA&quot; wsp:rsidRDefault=&quot;006956CA&quot; wsp:rsidP=&quot;00AF04BF&quot;&gt;
        ///          &lt;w:pPr&gt;
        ///            &lt;w:pStyle w:val=&quot;Prrafodelista&quot;/&gt;
        ///            &lt;w:listPr&gt;
        ///              &lt;w:ilvl w:val=&quot;0&quot;/&gt;
        ///              &lt;w:ilfo w:val=&quot;4&quot;/&gt;
        ///              &lt;wx:t wx:val=&quot;ý&quot;/&gt;
        ///              &lt;wx:font wx:val=&quot;Wingdings&quot;/&gt;
        ///            &lt;/w:listPr&gt;
        ///            &lt;w:rPr&gt;
        ///              &lt;w:rFonts w:cs=&quot;Calibri&quot;/&gt;
        ///              &lt;w:lang w:val=&quot;EN-US&quot;/&gt;
        ///            &lt;/w:rPr&gt;
        ///          &lt;/w:pPr&gt;
        ///          &lt;w:proofErr w:typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagOK {
            get {
                return ResourceManager.GetString("tagOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:tblPr&gt;
        ///    &lt;w:tblW w:w=&quot;0&quot; w:type=&quot;auto&quot; /&gt;
        ///    &lt;w:tblBorders&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot; w:space=&quot;0&quot;
        ///      w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot; w:space=&quot;0&quot;
        ///      w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:bottom w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot;
        ///      w:space=&quot;0&quot; w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:right w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot; w:space=&quot;0&quot;
        ///      w:color=&quot;auto&quot; /&gt;
        ///      &lt;w:insideH w:val=&quot;single&quot; w:sz=&quot;4&quot; wx:bdrwidth=&quot;10&quot;
        ///      w:sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tagStyle {
            get {
                return ResourceManager.GetString("tagStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:tbl&gt;.
        /// </summary>
        internal static string tagTable {
            get {
                return ResourceManager.GetString("tagTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/w:tbl&gt;.
        /// </summary>
        internal static string tagTableEnd {
            get {
                return ResourceManager.GetString("tagTableEnd", resourceCulture);
            }
        }
    }
}
